name: Update nightly tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 */1 * *'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Update nightly tag
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        uses: ydataai/create-tag@v1
        with:
          tag: "nightly"
          message: "Nightly Tag"
